### ISSUE TITLE
Ability to pass fetch instead of window.fetch 

### ISSUE THREAD

**Issue by go-aegian** [bufbuild/protobuf-es#1014]
Not sure if this is me doing something wrong, is there a way  in SvelteKit to pass fetch instead of window.fetch ?

buf.knit.gateway.v1alpha1.KnitService/Fetch using `window.fetch`. For best results, use the `fetch` that is passed to your `load` function:

**Comment by timostamm** [comment]
Protobuf-ES doesn't use `fetch` at all. 

Did you mean to file an issue in https://github.com/bufbuild/knit-ts ?
