### ISSUE TITLE
%1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by eyouyou** [bufbuild/protobuf-es#137]
`protoc -I . --es_out="D:\*\proto\/../packages/grpc/src" --es_opt=target=ts --plugin=protoc-gen-es="D:\*\proto\/../node_modules/.bin/protoc-gen-es" ./*.proto  
--es_out: protoc-gen-es: %1 is not a valid Win32 application.`

### Environment:
version: 0.0.7
package manager: pnpm

**Comment by kevpie** [comment]
Try something like `--plugin=protoc-gen-es=.\\node_modules\\.bin\\protoc-gen-es` if you are using windows protoc. 

Not sure if you'll need a `.cmd` extension or similar.

I found similar examples from https://github.com/hopin-team/twirp-ts under **`using protobuf-ts on windows, Git Bash`**

**Comment by timostamm** [comment]
Thanks for the report. `protoc-gen-es` is a JavaScript file that executes the platform-specific binary. `npm` and `pnpm` should add a `.cmd` file (or a `.bat` file for old windows versions). So it might indeed be necessary to add the `.cmd` extension to the plugin name. I have to admin that this is not exhaustively tested yet - please do let us know if there are any issues.

**Comment by timostamm** [comment]
Hey @eyouyou, [v0.0.9](https://github.com/bufbuild/protobuf-es/releases/tag/v0.0.9) has just been released, switching to a more typical executable written in JavaScript. This may have fixed an issue on Windows, if there was one.

npm will add an auxiliary `.bat` or `.cmd` file next to `protoc-gen-es`, making the executable behave like a regular binary in practice.

Closing this. Let us know if the problem persists.

**Comment by tjones0808** [comment]
> Try something like `--plugin=protoc-gen-es=.\\node_modules\\.bin\\protoc-gen-es` if you are using windows protoc.
> 
> Not sure if you'll need a `.cmd` extension or similar.
> 
> I found similar examples from https://github.com/hopin-team/twirp-ts under **`using protobuf-ts on windows, Git Bash`**

worked

**Comment by boan-anbo** [comment]
> Hi there! I'm still encountering this on buf `1.30.0`
> 
> ```
> - plugin: oneofcase
>    path: ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts 
>    opt: target=ts
>    out: .
> ```
> 
> I can get the plugin to work on MacOS with this line at the beginning of the plugin .ts
> 
> > #!/usr/bin/env -S npx tsx
> 
> But on Windows it reports:
> 
> ```shell
> Failure: plugin oneofcase: fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; context canceled; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins/oneof-
> enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; context canceled; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a vali
> d Win32 application.; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-
> oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins/oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.; fork/exec ./plugins
> /oneof-enum-plugin/protoc-gen-oneofcase.ts: %1 is not a valid Win32 application.
> ```
> 
> **What's the current way to set up a plugin in buf gen?**
> 
> buf gen commanline:
> 
> > npx buf generate --output ...

Found solution: https://github.com/bufbuild/protobuf-es/blob/a0ba45a50ae94d52de1a490f80ea8df58e1d8434/packages/protoplugin-example/buf.gen.yaml#L13

And remove the initial shebang line.

**Comment by Nukelimer** [comment]
C:\Users\Nukelimer\Desktop\Projects\currency-converter\api>  protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./api --ts_proto_opt=nestJs=true ./proto/todo.proto
--ts_proto_out: protoc-gen-ts_proto: %1 is not a valid Win32 application.

**Comment by timostamm** [comment]
@Nukelimer, our plugin executable is `./node_modules/.bin/protoc-gen-es`. It's possible that you try to run a file that does not exist.

See [here](https://www.npmjs.com/package/@bufbuild/protoc-gen-es) for more information on how to use it with `buf` or `protoc`.
