### ISSUE TITLE
Is `moduleResolution=Node` a requirement?

### ISSUE THREAD

**Issue by faustbrian** [bufbuild/protobuf-es#209]
I'm currently migrating a project to ESM and noticed that all my `buf generate` commands fail when I use `"moduleResolution": "NodeNext"` in my `tsconfig.json` files. Is the use of `"moduleResolution": "Node"` an absolute requirement or is there some way to work around this so that `NodeNext` can be used as resolution mechanism?

```
source/index_pb.ts:42:38 - error TS2576: Property 'fromBinary' does not exist on type 'TransactionChecksum'. Did you mean to access the static member 'TransactionChecksum.fromBinary' instead?

42     return new TransactionChecksum().fromBinary(bytes, options);
                                        ~~~~~~~~~~

source/index_pb.ts:46:38 - error TS2576: Property 'fromJson' does not exist on type 'TransactionChecksum'. Did you mean to access the static member 'TransactionChecksum.fromJson' instead?

46     return new TransactionChecksum().fromJson(jsonValue, options);
                                        ~~~~~~~~

source/index_pb.ts:50:38 - error TS2576: Property 'fromJsonString' does not exist on type 'TransactionChecksum'. Did you mean to access the static member 'TransactionChecksum.fromJsonString' instead?

50     return new TransactionChecksum().fromJsonString(jsonString, options);
```

**Comment by smaye81** [comment]
Hey @faustbrian.  `moduleResolution="Node"` is definitely not a requirement.  After some digging it turns out that this is due to a missing `types` property in the conditional exports in our `package.json` file.  I will put up a PR to fix this.  Thanks for pointing this out!
