### ISSUE TITLE
Wrong import when using `--es_opt=target=ts`

### ISSUE THREAD

**Issue by stephanos** [bufbuild/protobuf-es#225]
👋 Hello,

I've noticed a problem when I import a type between my protos while using `--es_opt=target=ts`.

in `a.proto`:
```
enum MyEnum {
  SOME_VAL = 0;
}
```

in `b.proto`:
```
import 'a.proto';

message MyMessage {
  MyEnum type = 1;
}
```

and when using
```
protoc -I proto/*.proto --es_opt=target=ts --plugin=protoc-gen-es=./node_modules/.bin/protoc-gen-es ...
```

the generated `b_pb.ts` contains

```
...
import {MyEnum} from "./a_pb.js";
...
```

which is invalid since the file name is of course `a_pb.ts`.

I guess it should either generate the import with the `.ts` suffix OR just leave it off since that's valid, too?

**Comment by smaye81** [comment]
hey @stephanos.  That is actually intentional.  We generate in accordance with ECMAScript module rules.  Are you seeing any sort of error?  If so, you may want to check out this page in our docs, which explains some issues with certain bundlers regarding the `.js` extension:

https://connect.build/docs/web/supported-browsers-and-frameworks/

**Comment by stephanos** [comment]
@smaye81 Thanks for the quick reply! I did get an error from Jest, but I see that there is a fix in the docs you linked to that I wasn't aware of. In that case, I'll close the issue.

**Comment by stephanos** [comment]
Hm, it's not quite working. I can't put it in `package.json` like the docs suggest since I have to separate Jest config files. Putting it in there like this

```
transform: {
    '^.+\\.ts?$': 'ts-jest'
  },
  moduleNameMapper: {
    "(.+)\\.js": "$1"
  },
  roots: ["<rootDir>/src/"],
  moduleFileExtensions: ['js', 'ts'],
  testRegex: "\\.test\\.ts$",
```

gives me

```
Could not locate module ../package.json mapped as:
    $1.
```

**Comment by smaye81** [comment]
Hmm, interesting.  We have a working Jest setup in our connect-web-integration repo [here](https://github.com/bufbuild/connect-web-integration/tree/main/react/cra).  Although this was generated with Create React App, so I'm wondering if CRA is doing some magic under the hood to make this work.

I see you're using `ts-jest`.  Can you confirm if the settings mentioned on [this page](https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/) help at all?

**Comment by stephanos** [comment]
@smaye81 Yeah, I think CRA is doing some magic there. In any case, by hard-coding the file I got it to work; I'm happy with this :) Thank you again for your assistance!

**Comment by smaye81** [comment]
OK, sounds good.  I am also going to create a from-scratch React project in our connect-web-integration repo just to see what the actual issue is since there's a bit of a gap in our docs.  Thanks for pointing this out!  Glad you're up and running.

**Comment by smaye81** [comment]
@stephanos I added an example using Jest and esbuild to our connect-web-integration repo [here](https://github.com/bufbuild/connect-web-integration/tree/main/react/esbuild).  I actually was able to get things running with mostly the same setup as we have documented, so I think our documentation may be ok.

At any rate, maybe this will provide some help in your issue from last week.  I know you mentioned you were working, but just wanted to let you know this was available.

**Comment by satetsu888** [comment]
Thanks for this issue and answer! This helps me so much.

I met a similar issue with using Next.js, but this is simply solved by add a resolve rule in webpack.
I am leaving this just for next one who came here using Next.js :)

Add below to `next.config.js`
```
  ...
  webpack: (config, options) => {
    config.module.rules.push({
      resolve: {
        extensionAlias: {
            '.js': ['.ts', '.js'],
        },
      }
    })
    return config
  },
  ...
```
