### ISSUE TITLE
can we enable discussions?

### ISSUE THREAD

**Issue by unicomp23** [bufbuild/protobuf-es#232]

**Comment by timostamm** [comment]
We are not enabling discussions on this repository at this point. If you have any general questions that do not feel right as an issue, please feel free to start a [discussion in the connect-web repository](https://github.com/bufbuild/connect-web/discussions), or join the community on [Slack](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w).
