### ISSUE TITLE
Expose well known types utils

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#257]
The `matchWkt` function from protoc-gen-es is rather useful also outside of protoc-gen-es. Can we move that to `@bufbuild/protoplugin` or even `@bufbuild/protobuf` and expose it there?

**Comment by smaye81** [comment]
Hey @fubhy.  Could you provide details on your use case?

**Comment by fubhy** [comment]
I'm writing a protoc-gen-validate implementation for typescript and currently working on these: https://github.com/bufbuild/protoc-gen-validate/blob/main/tests/harness/cases/wkt_wrappers.proto

... for which I need pretty much the same information as you need here for protoc-gen-es.

**Comment by smaye81** [comment]
OK, sounds good.  Your use case makes sense, but there's some implications we need to think through regarding how we expose it.  Going to keep this issue / discussion open.

**Comment by smaye81** [comment]
@fubhy Landed a change that exposes the WKT util method you mentioned as `reifyWkt`.  

https://github.com/bufbuild/protobuf-es/pull/263
