### ISSUE TITLE
`map<k,v>` doesn't support bigint and boolean keys

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#258]
The `map<k,v>` field type currently uses a simple object as a representation. However, that doesn't work for `bigint` keys. 

Same for `boolean` keys. That's also theoretically supported and there's even a possible pitfall here (stringified serializing and deserializing booleans that is). So I'd personally prefer to use `Map<k, v>()` here unless something speaks against that?

**Comment by smaye81** [comment]
Hey @fubhy.  That was actually a design choice when writing the library.  See our docs on maps [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/generated_code.md#map-fields).

That being said, though, we are investigating whether we still want to stick with this simple object representation or instead migrate to using an ES `Map`.  It is on our roadmap as something to decide before our v1.0 release, which should be out soon.

I'll keep this issue open until a decision is reached.  Thanks for the issue, definitely on our plate to consider.

**Comment by fubhy** [comment]
Sorry, I must've missed that in the docs.

**Comment by smaye81** [comment]
No worries.  Something we're thinking about also.

**Comment by smaye81** [comment]
Hi @fubhy.  After a lot of deliberation on this, we've decided not to switch to `Map` at this time and are sticking with simple objects.   Apologies for any inconveniences this causes.
