### ISSUE TITLE
Wrong float values via `findCustomMessageOption`

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#280]
I ran into a float decoding issue with the output of `findCustomMessageOption()` when generating code for float validation rules as defined here:

https://github.com/bufbuild/protoc-gen-validate/blob/main/tests/harness/cases/numbers.proto#L8

The value `1.23` in that `float.const` option is turned into `1.2300000190734863` once it reaches my protoplugin code generator here.

As seen here (in the output): https://github.com/fubhy/protobuf-zod/blob/main/packages/protoc-gen-validate-zod/tests/harness/cases/numbers_zod.ts#L47-L51

Is that a known issue or am I doing sth. wrong or is there a bug with that? I can dig deeper myself if nothing comes to mind right away but I thought I'd ask first ...

**Comment by fubhy** [comment]
Note:

The output for that is produced here: https://github.com/fubhy/protobuf-zod/blob/main/packages/protoc-gen-validate-zod/src/scalar.ts#L301

And this is where I retrieve that `FieldRules` instance: https://github.com/fubhy/protobuf-zod/blob/main/packages/protoc-gen-validate-zod/src/field.ts#L66

**Comment by fubhy** [comment]
Seems to be a Double vs. Float conversion issue.

**Comment by smaye81** [comment]
I am able to recreate this @fubhy.  We will take a look.  Thanks for reporting.

**Comment by fubhy** [comment]
@smaye81 Thanks. I wrote a test case for that here: https://github.com/bufbuild/protobuf-es/compare/main...fubhy:custom-message-option-float-bug?expand=1

**Comment by fubhy** [comment]
I guess it boils down to this ...

```
const view = new DataView(new ArrayBuffer(16));
view.setFloat32(0, 1.23, true);
view.getFloat32(0, true); // 1.2300000190734863
````

Which, I guess, is expected.

**Comment by smaye81** [comment]
Yeah meant to respond.  After some investigation to verify we are parsing these correctly, this actually is expected just by the nature of precision with floating-point in JavaScript.  There's really not much we can do to alleviate it, since it's part of the language itself.
