### ISSUE TITLE
Use extensionless imports in gereated files

### ISSUE THREAD

**Issue by rideg** [bufbuild/protobuf-es#282]
When I use the command:

protoc -I . --es_out build/js --es_opt target=ts a.proto b.proto

and assume that a.proto imports b.proto the generated file (a_pb.ts) will have an import something like this:

```Typescript
import {SomeProto} from "./b_pb.js"
```

This usually works fine, but I encountered an issue running jest tests where I got an error that it cannot find module "./b_pb.js"

As a workaround I added an extra step to the build that removes the extension from the imports:

```bash
find ./build/js -name '*.ts' | xargs -I{} sed -ibak `s/_pb\.js/_pb/g' {}
find ./build/js -name '*tsbak' | xargs -I{} rm -rf {}
```

After this everything worked ok.

**Comment by fubhy** [comment]
The `.js` extension is actually expected (see https://nodejs.org/api/esm.html#import-specifiers).

I'm not sure if it makes sense for `protoplugin` to offer an option to NOT have the `.js` import specifier suffix. It should certainly be the default.

**Comment by smaye81** [comment]
Yep, that is indeed intended as @fubhy said.  However, you shouldn't have to perform that extra step.  What module loader/bundler are you using?

We have some documentation [here](https://connect.build/docs/web/supported-browsers-and-frameworks) for dealing with the extension issues with different libraries.  The docs are for Connect-Web, but the same concept also applies to Protobuf-ES.  

Take a look at the docs and let us know if they address your scenario.  If not, we can help iron out any issues.

**Comment by rideg** [comment]
@fubhy Sorry for my ignorance, but I've never seen typescript files using extension in the import. Especially since tsc has the error "TS2691: An import path cannot end with a '.ts' extension. Consider importing" where they encourage not using any extensions. After some research now I understand the reasoning behind adding the .js extension and I can accept it. Thank you for sharing the link.

@smaye81 I checked the repo you shared and based on that I was able to update my jest.config.ts and now it works without using sed. Thank you! The solution was adding

```Typescript

moduleNameMapper {
  "^(.+)_pb\\.js$": "$1_pb"
}
```
to the config.

Thank you for the quick and helpful response! I'll close this issue.

**Comment by bgdnxt** [comment]
we got the same issue when using buf build also. with following build config
```sh
  - remote: buf.build/bufbuild/plugins/es
    out: gen/ts
    opt:
      - target=ts

```
all generated files are `.ts` extension. but the import lines still in `.js` which cause the error. we change it by hand as work around at the moment.
