### ISSUE TITLE
Add `google.protobuf.Any.unpack` function

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#285]
Currently, in order to unpack into a message instance, you have to do:

```typescript
  const any = ... // Some arbitrary `google.protobuf.Any` any.
  const message = registry.findMessage(typeName);
  const instance = new message!();
  any.unpackTo(instance);
```

It would be great if `google.protobuf.Any` was generated with a utility for that accepting a `typeRegistry` as input.

**Comment by smaye81** [comment]
Hey @fubhy.  This was actually something on our roadmap also.  Any interest in putting up a PR?

**Comment by fubhy** [comment]
Yep. Will do!

**Comment by fubhy** [comment]
https://github.com/bufbuild/protobuf-es/pull/288
