### ISSUE TITLE
Proposal: Inherit constructor and static methods from base Message class

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#290]
I was wondering why we are generating static methods instead of simply inheriting them from the base class. Is there a reason for that?

With these messages also also used in the frontend as part of e.g. connect-web, I think we have to be extra careful not to add too much weight especially for projects with a lot of messages.

I was thinking of doing something like this with the base Message class:

```typescript
export class Message<T extends Message<T> = AnyMessage> {
  static readonly runtime: ProtoRuntime;
  static readonly typeName: string;
  static readonly fields: FieldList;

  static fromBinary<T extends Message<T>>(
    this: MessageType<T>,
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): T {
    return new this().fromBinary(bytes, options);
  }

  static fromJson<T extends Message<T>>(
    this: MessageType<T>,
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): T {
    return new this().fromJson(jsonValue, options);
  }

  static fromJsonString<T extends Message<T>>(
    this: MessageType<T>,
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): T {
    return new this().fromJsonString(jsonString, options);
  }

  static equals<T extends Message<T>>(
    this: MessageType<T>,
    a: T | PlainMessage<T> | undefined | null,
    b: T | PlainMessage<T> | undefined | null
  ): boolean {
    return this.runtime.util.equals(this, a, b);
  }

  constructor(data?: PartialMessage<T>) {
    const self = <typeof Message<T>>this.constructor;
    self.runtime.util.initPartial(data, this as any);
  }

  // ...
}
```

Are there any reasons why this wouldn't work at runtime?

**Comment by jcready** [comment]
You'll get CSP errors if you try to `new this.constructor()`. Instead just `new this()`.
```ts
class A {
  static foo() {
    return new this();
  }
  constructor() {
    this.bar = 1;
  }
}

class B extends A {
  constructor() {
    super();
    this.baz = 2;
  }
}

const b = B.foo() // B {bar: 1, baz: 2}
```

**Comment by fubhy** [comment]
Ah, yeah... I ran into that in the past. Anyways, this is just sudo code for now to illustrate the proposal.

**Comment by timostamm** [comment]
@fubhy, we ran into some type issues with this. It has been a while, and unfortunately I can't tell you whether it was related to to an older version of TypeScript (we test down to 4.1.2), or compilation to .d.ts losing type information, or something else. 

The code compresses very well, but it would obviously be pretty neat if we could get around it!

**Comment by fubhy** [comment]
@timostamm Do you think it would make sense for me to try and experiment with this a bit? Does @smaye81 maybe remember what the limitation was or one of your colleagues? I'd be keen to give it a shot unless you can confirm it's indeed proven to be a dead-end :-)

**Comment by smaye81** [comment]
Sorry for the delay.  I don't actually remember what it was either.  If you are able to get around it though, as @timostamm said, we'd be all ears!

**Comment by smaye81** [comment]
Hi @fubhy just doing some maintenance of the repo. Were you still working on this PR? If so, no worries. If not, was going to close it due to staleness.

**Comment by fubhy** [comment]
> Hi @fubhy just doing some maintenance of the repo. Were you still working on this PR? If so, no worries. If not, was going to close it due to staleness.

Sorry, saw your message but then forgot to reply. No, I'm currently not working on this. I'm neck deep in other unrelated work atm. and won't have time for OSS in the next few days / weeks.

**Comment by smaye81** [comment]
No worries. I'm going to close this, but if you get back around to it, feel free to reopen. Thanks!
