### ISSUE TITLE
Set max repeated length for DOS protection

### ISSUE THREAD

**Issue by dapplion** [bufbuild/protobuf-es#299]
**Rationale**

protobuf is very versatile format and can exacerbate DOS issues with amplification attacks. In Javascript 1 byte of protobuf can expand to ~80 bytes using lists.

In many applications it's unreasonable to allow lists of lengths of hundred thousands, and a sane default is known in advance.

**Proposal**

Add an option to limit repeated length at decode time. If more items that said length are found, ignore them or throw an error. proto2 or proto3 format could accommodate the feature with:

- With custom options
```proto
message Sample {
  repeated string str = 1 [max_length_ignore = 100] ;
}
```

- Prepending comments to the field
```proto
message Sample {
  repeated string str = 1; // __max_length_ignore=100
}
```

**Comment by smaye81** [comment]
Hi @dapplion.  Appreciate the issue, but I don't think this is something we plan on implementing any time soon.  We're also not aware of any other implementation providing such a feature.  

Just for a possible alternative, you can maybe attempt to write your own parser based on what we have and potentially monkeypatch it?   The relevant code is [here](https://github.com/bufbuild/protobuf-es/blob/main/packages/protobuf/src/private/binary-format-common.ts#L95).

**Comment by dapplion** [comment]
> Just for a possible alternative, you can maybe attempt to write your own parser based on what we have and potentially monkeypatch it? The relevant code is [here](https://github.com/bufbuild/protobuf-es/blob/main/packages/protobuf/src/private/binary-format-common.ts#L95).

Thanks for the pointer will look into it. For all consumers of the protocol I work with (Rust, Go, Java, Nim) all had to write their own DOS safe protobuf decoders. Currently I use the generator then modify the output since our protobuf structures do not change often.

**Comment by smaye81** [comment]
Hi @dapplion.  Going to close this issue since we don't plan to implement this any time soon.  If you have any problems or questions, though, feel free to open a new issue.
