### ISSUE TITLE
`T` is not assignable to `PartialMessage<T>` for messages with `Oneof` fields

### ISSUE THREAD

**Issue by MonoidMusician** [bufbuild/protobuf-es#314]
For messages with `Oneof`, the generated message type `T` is not assignable to `PartialMessage<T>` because the generated message type includes a case `{ case: undefined, value?: undefined }` that is not added by `PartialMessage`.

I have a patch for this which seems to fix it for our use-case (both of the additions are necessary):
https://github.com/id3as/protobuf-es/commit/c8994e4baa29e694a49ec277ba54896e203b0ad7

**Comment by MonoidMusician** [comment]
Sure, here's a small repro, it just needs a message that contains a message with a `oneof` field: https://gist.github.com/MonoidMusician/e0d3d29c6ce6973dc41473aac011db7c

I don't have enough experience with TypeScript to know why it's dropping the undefined case, but the error is clearly that `Foo` contains `{ case: undefined; value?: undefined; }` and `PartialMessage<Foo>` doesn't.

```
Type '{ value: string; case: "fieldCase"; } | { case: undefined; value?: undefined; }' is not assignable to type '{ value: string; case: "fieldCase"; }'.
```

If I add another case, that shows up, so it isn't just dropping extra cases.
```
Type '{ value: string; case: "fieldCase"; } | { value: number; case: "otherCase"; } | { case: undefined; value?: undefined; }' is not assignable to type '{ value: string; case: "fieldCase"; } | { value: number; case: "otherCase"; }'.
```

**Comment by smaye81** [comment]
Hmm, I still can't seem to recreate that issue here.  What version of Protobuf-ES are you using?  Also, what version of TypeScript?

**Comment by MonoidMusician** [comment]
Huh, upgrading TypeScript `4.8.4 -> 4.9.3` fixes it. Not sure why that is.

**Comment by jcready** [comment]
Is the fact that OP has `strictNullChecks` turned off the issue? https://gist.github.com/MonoidMusician/e0d3d29c6ce6973dc41473aac011db7c#file-tsconfig-json-L12

**Comment by MonoidMusician** [comment]
Yes, changing that to true also seems to fix it on 4.8.4 … but leaves me with a different pile of errors that I don't want to fix right now 😂

**Comment by smaye81** [comment]
Yeah I do see the errors now if I turn that off (and also `strictPropertyInitialization`).  @MonoidMusician are you seeing a different pile of errors within Protobuf-ES or your own code when you set that to true?

**Comment by MonoidMusician** [comment]
I was referring to more errors within our own code, sorry for the confusion. No errors from Protobuf-ES with either of those changes.

**Comment by smaye81** [comment]
OK, cool.  Going to close this then.  If you notice another problem, feel free to open a new issue.

**Comment by smaye81** [comment]
Agreed.  I think we just need to mention that we run our compatibility tests against the default `tsconfig` settings that are generated when running `tsc --init` (with some small exceptions on newer TS versions) and therefore, those settings are what we officially support.  I will add this to the docs.
