### ISSUE TITLE
need support for delimited wire format

### ISSUE THREAD

**Issue by cc32d9** [bufbuild/protobuf-es#364]
We use the delimited wire format in the project: each message is prepended with varuint32 indicating its length. This corresponds to `parseDelimitedFrom` in Google protobuf, or `decodeDelimited()` in protobufjs.

Similar functionality is needed in protouf-es, both for reading and writing.

**Comment by timostamm** [comment]
Hey @cc32d9, you are referring to the length-delimitation described in https://github.com/protocolbuffers/protobuf/issues/10229, correct?

This is a reasonable request. Can I ask in what context you are using this feature? Are you reading from a stream, or are you looking into splitting a buffer into messages?

**Comment by cc32d9** [comment]
hi, I'm designing and prototyping this protocol: https://github.com/fixpayments/pbtx_rpc

The MVP will use HTTP POST requests, so message framing is not a problem because there's content-length header. But The protocol is designed for IoT devices, and they may need different ways of transport. For example, a sequence of records on an SD card. Or a LoRa connection which is totally unreliable and dropping messages is a normal daily life there. But LoRa is an extreme example and anyway it needs additional mechanisms for delivery assurance. But a possibility to send a sequence of messages in a single HTTP POST call would be appealing.

So, ideally, we need a mechanism to read a sequence of messages from a stream, so that each message is prepended by its varint32 length. Also, a corresponding message writer which can produce such a stream.

**Comment by timostamm** [comment]
Thanks for the context, @cc32d9. 

Unfortunately, we don't have a single standard for streams in JavaScript, but I think we can provide basic functions to serialize and parse, and also some helpful functions for implementing streams in Node or with WHATWG streams. 

Expect a PR soonish :)

**Comment by timostamm** [comment]
@cc32d9, this PR implement basic support for size-delimited messages: https://github.com/bufbuild/protobuf-es/pull/387

Let us know if that would work for your use case.

**Comment by timostamm** [comment]
@cc32d9, this is now available in [v1.1.0](https://github.com/bufbuild/protobuf-es/releases/tag/v1.1.0). 

You can find some documentation [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#size-delimited-messages).
