### ISSUE TITLE
Base64 

### ISSUE THREAD

**Issue by balzdur** [bufbuild/protobuf-es#366]
**Context:**
I receive from an Rest API a base64 encoded Message. In order to use `Message.fromBinary(...)` I need to convert it.

The code needs to work on both NodeJS and Browser environment.

**Question:**
After digging in the code source of the package, I found this file `packages/protobuf/src/proto-base64.ts`.

The methods are accessible from the public API of the package but not discussed in the documentation.

My question: is it something I can rely on or should it be considered unstable (meaning for implementation detail it can change in future releases) ?

**Comment by timostamm** [comment]
Hey Thomas, the base64 implementation can be considered stable. Even though we do not have dedicated unit tests for it, the implementation is decently covered by the [conformance tests](https://github.com/bufbuild/protobuf-es/tree/main/packages/protobuf-conformance) (`bytes` fields in JSON).

That said, some unit tests next to the file `packages/protobuf-test/src/proto-int64.test.ts`, or a short usage example at the bottom of [docs/runtime-api.md](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md) would probably be a good call. We'd gladly accept a contribution for either, but I can tell you that we will not change the existing implementation in a non-major release (bugfixes _may_ be an exception).

**Comment by timostamm** [comment]
Closed by https://github.com/bufbuild/protobuf-es/pull/368 🎉
