### ISSUE TITLE
makeUrl generates an incorrect url

### ISSUE THREAD

**Issue by MinchulChae** [bufbuild/protobuf-es#372]
Hi, thanks for providing protobuf-es to generate ts files.

It generates ts files very well, but it doesn't work for me.
I am using <https://github.com/grpc-ecosystem/protoc-gen-grpc-gateway-ts> to generate the ts files. the example is as below.
The url is `/api/v1/search/projects`. It works very well.
```
export class CoreService {
  static SearchProjects(req: SearchRequest, initReq?: fm.InitReq): Promise<ProjectSearchResults> {
    return fm.fetchReq<SearchRequest, ProjectSearchResults>(`/api/v1/search/projects?${fm.renderURLSearchParams(req, [])}`, {...initReq, method: "GET"})
  }
}
```

Protobuf-es generates different typescript as below.
```
export const CoreService = new ServiceType("ai.xxx.xxx.api.v1.CoreService", [{ name: "SearchProjects", options: { "google.api.http": { get: "/api/v1/search/projects" } }, I: SearchRequest, O: ProjectSearchResults }]);

export class CoreServiceClient implements ICoreServiceClient, ServiceInfo {
    ...
    searchProjects(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, ProjectSearchResults> {
        const method = this.methods[96], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchRequest, ProjectSearchResults>("unary", this._transport, method, opt, input);
    }
    ...
}
```

It generates the incorrect url `/ai.xxx.xxx.api.v1.CoreService/SearchProjects` since `makeUrl` doesn't use the `[options](options: { "google.api.http": { get: "/api/v1/search/projects" } })`. I couldn't find any documents about how to use `options: { "google.api.http": { get: "/api/v1/search/projects" } }` as the request url.
```
makeUrl(method, options) {
        let base = options.baseUrl;
        if (base.endsWith('/'))
            base = base.substring(0, base.length - 1);
        return `${base}/${method.service.typeName}/${method.name}`;
    }
```

I may use Protobuf-ts incorrectly or *.proto files may have incorrect definitions but I couldn't find any documents or examples about that. Also, the *.proto files work with `protoc-gen-grpc-gateway-ts` well.
thank you for reading this!

**Comment by timostamm** [comment]
Hey Minchul, you are correct, the [GrpcWebFetchTransport of protobuf-ts](https://github.com/timostamm/protobuf-ts/blob/02c82bdc66e1cf2bea199906c580e9d75ff93bcf/packages/grpcweb-transport/src/grpc-web-transport.ts#L65) does not support the `google.api.http` options. Unfortunately, I'm not sure what the best approach is for grpc-gateway. I think their code generator [protoc-gen-grpc-gateway-ts](https://github.com/grpc-ecosystem/protoc-gen-grpc-gateway-ts) is probably the best bet.

The grpc-gateway translates between plain JSON requests and gRPC services. The `GrpcWebFetchTransport` can be used if you don't use grpc-gateway, and your server speaks gRPC-web along with gRPC (like [.NET](https://devblogs.microsoft.com/dotnet/grpc-web-for-net-now-available/), or [connect-go](https://connect.build/)), or if you have a proxy in front of your gRPC service that makes it available as gRPC-web.

We believe that gRPC-web or the Connect protocol with a much more direct way to use services from the frontend is a better developer experience overall than `google.api.http` annotations and a translating proxy, and we don't have an implementation for it. Neither has protobuf-**ts**, but with protobuf-**es**, you could [write your own plugin](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md) for the grpc-gateway.

**Comment by MinchulChae** [comment]
Thank you so much for the quick response 👍
