### ISSUE TITLE
Type resolution for generated code struggles when using `NodeNext`

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#396]
`The inferred type of 'runtime' cannot be named without a reference`

The generated code from `protoc-gen-es` currently causes problems with NodeNext module resolution. I'm not a tsconfig wizard (who really is though?) so there may be a misconfiguration on my side. However, `tsc` struggles with the generated `runtime` property on messages.

```typescript
  ...

  static readonly runtime = proto3; // This is where it errors with "The inferred type of 'runtime' cannot be named without a reference".
  static readonly typeName = "sf.substreams.v1.Clock";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "number", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "timestamp", kind: "message", T: Timestamp },
  ]);

  ...
```

Adding an explicit type hint like for FieldList below solves it, but I'm not sure if that's the route you want to take. If it is, I'm happy to whip up a PR for that.

I put together a simple reproduction here:  https://github.com/fubhy/protoc-gen-es-repro

**Comment by timostamm** [comment]
Thanks for flagging this. We run the TypeScript compiler with "NodeNext" module resolution [here](https://github.com/bufbuild/protobuf-es/blob/3837af844863be6e39e2cf21639eca1e49811ead/packages/protobuf-test/typescript/tsconfig.4_8_4.json#L15), so it's not clear to me why it doesn't cause a test failure. 

I think the steps forward here are to make the tests with NodeNext fail, and then fix the issue with a type hint `runtime: ProtoRuntime`.

**Comment by fubhy** [comment]
The reason why it's failing in those tests is that those tests are not emitting declaration files.
