### ISSUE TITLE
Service declarations

### ISSUE THREAD

**Issue by unicomp23** [bufbuild/protobuf-es#401]
Why isn't there codegen for the service declarations in the proto?  Is there a way to generate twirp endpoints w/ protobuf-es?  Or is there something I'm missing?

**Comment by unicomp23** [comment]
connect-es, lol, found it

**Comment by smaye81** [comment]
Haha, glad you found it.  Also, regarding your Twirp question, we provide [an example](https://github.com/bufbuild/protobuf-es/tree/main/packages/protoplugin-example) in this repo for generating Twirp endpoints using the plugin framework from Protobuf-ES.

**Comment by unicomp23** [comment]
Awesome, thank you! @smaye81 

I'm expecting a "no" on this one.  Has anything appeared for keeping the swagger pontifs happy?

**Comment by smaye81** [comment]
Do you mean a custom plugin for generating Swagger docs from Protobuf?  We don't support one ourselves for that purpose, but there are definitely others in the ecosystem.
