### ISSUE TITLE
Allow disabling variable naming style enforcement in @bufbuild/protoc-gen-es generator

### ISSUE THREAD

**Issue by silvialeung** [bufbuild/protobuf-es#418]
Current script transforms field names in snake case to pascal case. (e.g. _id becomes Id)
It would be nice to have a plugin option to keep the original field name. Something like namingRuleEnforce=false.

**Comment by smaye81** [comment]
Hi @silvialeung.   Apologies but this is not something we plan to implement at this time.  Our approach has been to limit the amount of plugin options to only those necessary to lower the barrier to entry to use the plugin.
