### ISSUE TITLE
generate_dependencies option

### ISSUE THREAD

**Issue by hugebdu** [bufbuild/protobuf-es#435]
Could be `@protobuf-es/plugin` does not generate sources for the dependencies, like `@protobuf-ts/plugin` did via the [generate_dependencies](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#the-protoc-plugin) option?

If that's the case, any plans to support it?

Thanks!

**Comment by timostamm** [comment]
Hey Daniel, we're very hesitant to add plugin options, see the [FAQ](https://github.com/bufbuild/protobuf-es/blob/main/docs/faq.md#what-is-your-stance-on-adding-options-to-the-plugin). I'd like to understand why this would be helpful to you. Do you know the `buf generate --include-imports` flag ([docs](https://buf.build/docs/reference/cli/buf/#buf-generate-include-imports))?

**Comment by hugebdu** [comment]
@timostamm thanks for your reply. 
For now I'm using `@protobuf-es/plugin` with `protoc`, not `buf` (migration phase from `protobuf-ts`).
Couldn't find the corresponding option for `protoc`.

**Comment by hugebdu** [comment]
Since `protoc` [can be used](https://github.com/bufbuild/protobuf-es/tree/main/packages/protoc-gen-es#with-protoc) officially, maybe it worth mentioning about this limitation?

alternatively reconsider adding that option :)
it does not change the "shape" of the generated code (like the camel case example in the FAQ), only makes this plugin more usable with `protoc`.

**Comment by timostamm** [comment]
From [google/protobuf/compiler/plugin.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto):

>   // The .proto files that were explicitly listed on the command-line.  **The**
  // **code generator should generate code only for these files**.  Each file's
  // descriptor will be included in proto_file, below.
  repeated string file_to_generate = 1;

The `generate_dependencies` option can be convenient because you don't have to manually maintain all proto files in the argument list to `protoc` (just your entry points), but it's bending the rules of the plugin contract. It's very unlikely that this option will be added to all existing plugins, so it's just not a great solution for the protobuf ecosystem.

Is this why you are using the option? So that you don't have to list all proto files on the command line?

**Comment by hugebdu** [comment]
> Is this why you are using the option? So that you don't have to list all proto files on the command line?

Indeed, listing all proto files explicitly can potentially generate plenty of non-needed code in our case.
I guess for now (until we migrate from `protoc` to `buf` + `workspaces`) we can have our own plugin, proprocessor, that expands the initial sources file set according to the imports.

Thanks anyway.

**Comment by timostamm** [comment]
Here's a quick stab at such a plugin:

```ts
#!/usr/bin/env -S npx tsx
import { runNodeJs } from "@bufbuild/protoplugin";
import { CodeGeneratorResponse } from "@bufbuild/protobuf";
import { execSync } from "node:child_process";
runNodeJs({
  name: "protoc-gen-eswithdeps",
  version: "v0.0.1",
  run(request) {
    request.fileToGenerate = request.protoFile.map(f => f.name ?? "");
    const resBytes = execSync("protoc-gen-es", {
      encoding: "buffer",
      input: request.toBinary(),
    });
    return CodeGeneratorResponse.fromBinary(resBytes);
  }
});
```

With `protoc`:

```
protoc -I . a.proto --plugin=protoc-gen-es=src/protoc-gen-eswithdeps.ts --es_out=.
```

Closing this issue, but pinning it so that others can see. Thanks for raising it!

**Comment by hugebdu** [comment]
@timostamm shouldn't it be something like:

```
request.fileToGenerate = [...request.fileToGenerate, ...request.protoFile.flatMap(f => f.dependency))];
```

**Comment by timostamm** [comment]
Good call, @hugebdu 👍

**Comment by pfontana10** [comment]
Hey guys,

@timostamm  is there any way to use this code with the latest versions of protobuf and protoc-gen-es v2.0?

Most of the methods have changed and now toBinary() and fromBinary() are separate functions of CodeGeneratorResponse and these functions need schemas of DescMessages.

Follow the docs, 
https://github.com/bufbuild/protobuf-es/blob/v2.0.0/MANUAL.md#migrating-from-version-1
I already updated the packages @bufbuild/protobuf@^2.0.0 @bufbuild/protoc-gen-es@^2.0.0

But the way to generate code now they use buf, needs to create a buf.gen.yaml
https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#how-to-generate-code

And if I want to write a custom plugin, I need to use buf.gen.yaml file
https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#writing-plugins

I appreciate any help provide

**Comment by pfontana10** [comment]
Hi everyone,

I ended up using version _2.0.0_ of protobuf this way. The methods like _toBinary_ and _fromBinary_ aren't attached to the object anymore, so you have to import from protobuf.
Another thing I've started doing is using schemas for CodeGeneratorRequest and CodeGeneratorResponse.

Here's an updated example:
```
#!/usr/bin/env -S npx tsx
import { runNodeJs } from '@bufbuild/protoplugin';
```

If you want to know more, you can check out this link:
https://github.com/bufbuild/protobuf-es/blob/v2.0.0/MANUAL.md#migrating-from-version-1

**Comment by pfontana10** [comment]
Hi everyone,

I ended up using version `2.0.0` of protobuf this way. The methods like `toBinary` and `fromBinary` aren't attached to the object anymore, so you have to import from protobuf.
Another thing I've started doing is using `schemas` for CodeGeneratorRequest and CodeGeneratorResponse.

Here's an updated example:
``` typescript
#!/usr/bin/env -S npx tsx
import { runNodeJs } from '@bufbuild/protoplugin';
import { toBinary, fromBinary } from '@bufbuild/protobuf';
import { CodeGeneratorRequestSchema, CodeGeneratorResponseSchema } from '@bufbuild/protobuf/wkt';
import { execSync } from 'node:child_process';

runNodeJs({
  name: 'protoc-gen-eswithdeps',
  version: 'v0.0.1',
  run(request) {
    request.fileToGenerate = request.protoFile
      .map((file) => file.name ?? '')
      .filter((file) => !file.startsWith('google/protobuf/'));

    const resBytes = execSync('protoc-gen-es', {
      encoding: 'buffer',
      input: toBinary(CodeGeneratorRequestSchema, request),
      maxBuffer: 1024 * 1024 * 1024,
    });

    return fromBinary(CodeGeneratorResponseSchema, resBytes);
  },
});
```

I checked out these [documentation](https://github.com/bufbuild/protobuf-es/blob/v2.0.0/MANUAL.md#migrating-from-version-1)
