### ISSUE TITLE
Verify our exports with arethetypeswrong

### ISSUE THREAD

**Issue by timostamm** [bufbuild/protobuf-es#456]
@fubhy pointed out https://arethetypeswrong.github.io/, written by one of the TypeScript maintainers.

A [project](https://github.com/arethetypeswrong/arethetypeswrong.github.io) that:
> attempts to analyze npm package contents for issues with their TypeScript types, particularly ESM-related module resolution issues.

We should take a look whether we can use this tool to verify that our build artifacts are exported correctly for the cases we do not cover ourselves in the tests. This will also be interesting for our other repositories (including @bufbuild/connect, which uses subpath exports).

**Comment by fubhy** [comment]
Mark Erikson has built a CI util that he uses in redux-thunk, redux-toolkit, etc.:

https://github.com/reduxjs/redux-toolkit/tree/master/examples/publish-ci/are-the-types-wrong

I was going to turn that into a reusable CLI & Github Action but didn't find the time yet.

**Comment by fubhy** [comment]
Discussion here: https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/15
