### ISSUE TITLE
MessageType & type guards?

### ISSUE THREAD

**Issue by hugebdu** [bufbuild/protobuf-es#482]
Is there anything in `protobuf-es` similar to the [protobuf-ts type guards](https://github.com/timostamm/protobuf-ts/blob/main/MANUAL.md#message-type-guards)?

could not find anything...

10x

**Comment by jcready** [comment]
`instaceof` https://github.com/bufbuild/protobuf-es/blob/main/docs/migrating.md#message-type-guards

**Comment by hugebdu** [comment]
@smaye81 the problem with `instanceof` is that it isn't very useful when all you have is either `PartialMessage<T>` or `PlainMessage<T>`. `protobuf-ts`'s `MT.is(...)` would handle these two.
