### ISSUE TITLE
Support allowing rewrite_imports to rewrite to URLs

### ISSUE THREAD

**Issue by NfNitLoop** [bufbuild/protobuf-es#483]
I believe @marekbuild told me to create this issue [in slack][1].

While buf supports a `rewrite_imports` option, it currently uses the `:` character to separate the search/replace terms of the rewrite. This means you can't rewrite to a URL, which is what I would like to be able to do in Deno.  [example code][2]. 

Right now, my workaround is to rewrite to a relative import, (which has [its own bug][3]), and then import and re-export the library from there.

Possible solutions:
 * Only split on the first `:`, thus allowing there to be `:` characters in the replace.
 * Allow escaping `:` characters. (But this might get a bit ugly because you might end up having to double-escape in yaml?) 

[1]: https://bufbuild.slack.com/archives/CRZ680FUH/p1682957084230579?thread_ts=1682811019.512249&cid=CRZ680FUH
[2]: https://github.com/NfNitLoop/deno-buf-connect/blob/74de9f7e4b1e8533db3d08d644cd571f887ef747/examples/oak-server-and-client/buf.gen.yaml#L13-L17
[3]: https://github.com/bufbuild/protobuf-es/issues/484

**Comment by smaye81** [comment]
I am going to merge this one into #293, since that one is that main Deno support PR.
