### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by bufdev** [bufbuild/protobuf-es#49]
Just a tracking task from review.

Important:

- [x] Conform to Go Style Guide :-) comments, splitting up of files, we should have a Golang eng do a pass with Timo
- [ ] DOCS - we should have extensive examples, justification about why this is better than alternatives
- [x] Have someone who is not Timo who is also an expert in JS do a deep dive, probably Paul, optimally get some external feedback
- [x] Update LICENSE to to 2021-2022 :white_check_mark:

Random comments:

- [ ] Evaluate moving `private/protoplugin` to new repository `protoplugin-es`? Probably not to start but worth a conversation.
- [ ] Move `cmd/internal` to `internal`.
- [x] See comments on https://github.com/bufbuild/protobuf-es/pull/35, tldr get rid of options if possible :white_check_mark:
- [x] Update go.mod to at least 1.17 (not really needed but) :white_check_mark:
- [x] Rename `GOOG` to `GOOGLE_` in the Makfile :-) :white_check_mark:

**Comment by tomchwojkofrank** [comment]
Moved to https://linear.app/bufbuild/issue/TCN-52/cleanup-protobuf-es49

**Comment by tomchwojkofrank** [comment]
Leaving open for now @SyrieBianco, cross linked from a `core` issue.

**Comment by timostamm** [comment]
@bufdev, regarding the open tasks here:

> DOCS - we should have extensive examples, justification about why this is better than alternatives

We have a some justification in the [top-level readme](https://github.com/bufbuild/protobuf-es#how-does-this-compare-to-protocs-javascript-generator), and more in the [migration docs](https://github.com/bufbuild/protobuf-es/blob/main/docs/migrating.md), which also has a feature comparison table. What do you think about that approach? Do we want to extend that to more alternative implementations (ts-proto, protobuf.js)?

> Evaluate moving private/protoplugin to new repository protoplugin-es? Probably not to start but worth a conversation.

Similar to Go's `protogen`, it's tied to the runtime library that also lives in this repo. I expect this to be the same for other implementations. We'd have to replicate most of the test infra to split this up, and I feel that would make it more brittle. 

>  Move `cmd/internal` to `internal`

That's how it was originally, but we had to introduce `private`, and I think having both `internal` and `private` will be pretty confusing to (JavaScript) developers.
