### ISSUE TITLE
`package-lock.json` missing `resolved` & `integrity` fields

### ISSUE THREAD

**Issue by felschr** [bufbuild/protobuf-es#526]
Hi, while trying to package `protoc-gen-es` for nixpkgs, I've ran into the issue that the `package-lock.json` doesn't contain any `resolved` & `integrity` fields: https://github.com/NixOS/nixpkgs/pull/243432#issuecomment-1635737984
These fields should exist according to the docs: https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json

This can likely be fixed by regenerating the lock file from scratch and/or updating to newer versions of npm.

**Comment by felschr** [comment]
So, this happened again.
I found this project (and improved it) that adds missing `resolved` & `integrity` fields to a `package-lock.json` without having to delete & regenerate it entirely:
https://github.com/jeslie0/npm-lockfile-fix

Maybe you could add that to a pre-commit hook or something to make sure the lockfile is valid.

**Comment by felschr** [comment]
Just noticed some cases that `npm-lockfile-fix` didn't cover yet and fixed them in https://github.com/jeslie0/npm-lockfile-fix/pull/3

**Comment by felschr** [comment]
Another issue I noticed is, that some `optionalDependencies` like `@bufbuild/buf-linux-x64` don't have entries in the `package-lock.json` anymore starting with `v1.3.2`.
The lock file should include resolved versions for all dependencies including optional ones.

**Comment by felschr** [comment]
@smaye81 can we reopen this issue or should I create a new one?

**Comment by smaye81** [comment]
Let's just reopen this one. I have a feeling this will happen again and don't want a proliferation of issues. I'll update the description.

**Comment by smaye81** [comment]
Actually let's also open a second issue for investigation into whether this can be fixed permanently. We'll regenerate the lock files in the meantime and associate that to this PR.

**Comment by felschr** [comment]
npm issues that track the problem of missing `integrity` & `resolved` fields:
https://github.com/npm/cli/issues/4263, https://github.com/npm/cli/issues/4460 https://github.com/npm/cli/issues/6301
