### ISSUE TITLE
`toPlainMessage` doesn't work with RSC and messages that contain binary data (`Uint8Array`)

### ISSUE THREAD

**Issue by fubhy** [bufbuild/protobuf-es#531]
I tried to utilize `toPlainMessage` to pass the `server<>client` boundary in a Next.js application (with React Server Components, RSC).

I ran into an obscure error there which appears to be caused by my messages containing WASM code (binary as `Uint8Array`).

I confirmed that "rehydrating" the same message (once via binary, once via plain message) doesn't yield the same result:

```typescript
// server.ts:
function MyServerComponent() {
  return <MyComponent plain={toPlainMessage(message)} binary={message.toBinary()} />
}

// client.ts
function MyClientComponent({ plain, binary }: { plain: PlainMessage, binary: any }) {
  const rehydratedBinary = MyMessageType.fromBinary(Uint8Array.from(binary));
  const rehydratedPlain = new MyMessageType(plain);

  console.log(rehydratedBinary.equals(rehydratedPlain)); // false

  return null;
}
```

However, it works fine for me if I use `.toBinary()` on the server and then "rehydrated" on the client using serde utils like this (using base64 to optimize for wire size):

```typescript
import { Message, MessageType, protoBase64 } from "@bufbuild/protobuf";

export type SerializedMessage<TMessage extends Message<TMessage>> = string & { __type: TMessage };

export function serializeMesage<TMessage extends Message<TMessage>>(message: TMessage) {
  return protoBase64.enc(message.toBinary()) as SerializedMessage<TMessage>;
}

export function deserializeMessage<TMessage extends Message<TMessage>>(
  type: MessageType<TMessage>,
  value: SerializedMessage<TMessage>,
) {
  return type.fromBinary(protoBase64.dec(value));
}
```

**Comment by jcready** [comment]
React Server Components require that all props are serializable to JSON. Your solution of passing the base64 encoded binary is valid, but you could probably simplify the process by just passing down the `MyMessageType.toJson()` in the props and then use `MyMessageType.fromJson()` inside the component. The `toJson` method already handles converting `bytes` (binary) message fields into their base64 encoded representation to make it serializable to JSON.

**Comment by fubhy** [comment]
Yeah. I've used `.toJson()` before. I only added this as an optimization because my messages are insanely large (several megabytes). Using base64 actually saves me a couple hundred kilobytes here.

**Comment by timostamm** [comment]
@srikrsna-buf, this should be resolved by https://github.com/bufbuild/protobuf-es/pull/533, right?

**Comment by srikrsna-buf** [comment]
Yes it can be closed

**Comment by srikrsna-buf** [comment]
[v1.3.1](https://github.com/bufbuild/protobuf-es/releases/edit/v1.3.1) has just been released with the fix.
