### ISSUE TITLE
All fields are optional in generated messages for proto2 schemas 

### ISSUE THREAD

**Issue by joemckenney** [bufbuild/protobuf-es#549]
When using proto2 in a project,  we expect the generated code to encode the optionality of a field in a message. 

Currently, all fields in the generated messages are optional (which makes sense in proto3 but doesn't quite align with a proto2 schema).

**Comment by czabaj** [comment]
Seems to be related to https://github.com/bufbuild/protobuf-es/issues/414

**Comment by joemckenney** [comment]
Spot on @czabaj, https://github.com/bufbuild/protobuf-es/issues/414 is the same.  Closing this one as a duplicate.
