### ISSUE TITLE
out folder should be created if it does not exist

### ISSUE THREAD

**Issue by alexeagle** [bufbuild/protobuf-es#553]
I'm working on #182 and ideally I'd like to generate code into a subfolder of the bazel output location, to avoid collisions with other protoc plugins that produce JavaScript (like the "Closure JS" flavor that protoc has built-in)

running with `--es_out=bazel-out/k8-fastbuild/bin/gen` should create a `gen` folder, but instead I see:

```
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc $@' '' '--plugin=protoc-gen-connect-es=bazel-out/k8-opt-exec-2B5CBBC6/bin/plugin/bufbuild/protoc-gen-connect.sh' '--connect-es_opt=target=js' '--connect-es_opt=keep_empty_files=true' '--connect-es_out=bazel-out/k8-fastbuild/bin' '--plugin=protoc-gen-es=bazel-out/k8-opt-exec-2B5CBBC6/bin/plugin/bufbuild/protoc-gen-es.sh' '--es_opt=target=js' '--es_opt=keep_empty_files=true' '--es_out=bazel-out/k8-fastbuild/bin/gen' '--descriptor_set_in=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/timestamp_proto-descriptor-set.proto.bin:bazel-out/k8-fastbuild/bin/example/thing/thing_proto-descriptor-set.proto.bin' example/thing/thing.proto)
# Configuration: 70b3ab185b7a98e28391fd0d3200c17daa7cb40789ff69aa97d418dd763a40da
# Execution platform: @local_config_platform//:host
ERROR: /home/alexeagle/Projects/stackb_rules_proto/example/thing/BUILD.bazel:145:14: Compiling protoc outputs for ["thing.proto"] failed: (Exit 1): bash failed: error executing command /bin/bash -c 'set -euo pipefail
mkdir -p ./example/thing
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc $@' '' ... (remaining 10 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
bazel-out/k8-fastbuild/bin/gen/: No such file or directory
```

**Comment by timostamm** [comment]
Hey Alex, glad to to hear you are working on integration with bazel!

Makes sense to generate code into subfolders, but the plugin is actually unaware of the `out` flag. See [here](https://buf.build/docs/reference/images#plugins) for an explanation how plugins work. It's up to the compiler to write files to disk at the `out` path, and unfortunately, `protoc` does not create a directory at the path if none exists. 

I think you will have to create the directory ahead of time.

**Comment by alexeagle** [comment]
Thanks, you're right it's a protoc bug.
Bazel doesn't have a way to "do something ahead of time", we'd have to wrap protoc itself with a bash script or something that can act as a parent process to shim that behavior in.
As it stands, we can just declare that users cannot have two different protoc plugins that want to emit the same file, because protoc doesn't allow a way to avoid the collision.
