### ISSUE TITLE
Can't use some imports from protoplugin with Node16 resolution

### ISSUE THREAD

**Issue by paul-sachs** [bufbuild/protobuf-es#586]
`@bufbuild/protoplugin/ecmascript` exposes some helpers like `localName` that seem to be untyped when using `moduleResolution: Node16` and `module: Node16` compiler settings:

<img width="842" alt="image" src="https://github.com/bufbuild/protobuf-es/assets/11449728/ea6a5cb0-ef68-474f-9b1a-95f2caf5d246">

Trying to compile results in the following error:

```
../protoplugin/dist/cjs/ecmascript/index.d.ts:6:47 - error TS2307: Cannot find module '@bufbuild/protobuf/dist/cjs/private/names.js' or its corresponding type declarations.

6 export declare const localName: typeof import("@bufbuild/protobuf/dist/cjs/private/names.js").localName, reifyWkt: typeof import("@bufbuild/protobuf/dist/cjs/private/reify-wkt.js").reifyWkt;
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../protoplugin/dist/cjs/ecmascript/index.d.ts:6:130 - error TS2307: Cannot find module '@bufbuild/protobuf/dist/cjs/private/reify-wkt.js' or its corresponding type declarations.

6 export declare const localName: typeof import("@bufbuild/protobuf/dist/cjs/private/names.js").localName, reifyWkt: typeof import("@bufbuild/protobuf/dist/cjs/private/reify-wkt.js").reifyWkt;
                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: ../protoplugin/dist/cjs/ecmascript/index.d.ts:6
```

See reproduction in PR https://github.com/bufbuild/protobuf-es/pull/585.

**Comment by timostamm** [comment]
This is an interesting issue. For the ESM exports of `@bufbuild/protoplugin`, we currently emit a .d.ts file that contains:

```ts
export declare const localName: typeof import("@bufbuild/protobuf/dist/cjs/private/names.js").localName
```

This import cannot be resolved with Node16 module resolution. If we were using Node16 module resolution, we would have gotten a compiler error here:

```
TS2742: The inferred type of 'localName' cannot be named without a reference to '../../../../node_modules/@bufbuild/protobuf/dist/cjs/private/names.js'. This is likely not portable. A type annotation is necessary.
```

`attw` cannot currently catch this kind of issue either, see https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/45. 

We can fix this issue, but we should definitely switch to building ESM with Node16 module resolution to guard against this error class.
