### ISSUE TITLE
Q: How to use `typeRegistry.findMessage`  only once?

### ISSUE THREAD

**Issue by RuslanGlaznyov** [bufbuild/protobuf-es#596]
I have a REST API and types of JSON  the same as proto files on the server side. 
To have all types from API I generated TS code and wrote a simple wrapper.
example: 
```ts
import { TodosResponse } from './proto-gen/.....'
class Api {
   todos() {
     const  result = await this.http.get(
      "/todos",
      );
   } 
  return TodosResponse.fromJSON(result)
}
```

This works perfectly I have a fully typed response! However, I faced an issue in some cases I had an error that not all types existed in the registry. 
The error looks something like this: 
```
cannot encode field <TodosResponse> to JSON: cannot encode field <pubKey> to JSON: cannot encode message google.protobuf.Any to JSON: "type.googleapis.com/crypto.ed25519.PubKey" is not in the type registry
```
So I did this: 

```ts
import { TodosResponse } from './proto-gen/.....'
class Api {
   todos() {
     const result = await this.http.get(
      "/todos",
      );
   } 
  return TodosResponse.fromJson(result as JsonValue, {
      typeRegistry: {
        findMessage(search: string) {
          if (search === "crypto.ed25519.PubKey") return PubKey;
        },
      },
   });
}
```
This works as expected.
But there are some disadvantages: 
1.  I need to write findMessege every time
2. When I call Api service and when I need to call method `toJSON` (in some cases I need raw data). I always have to add `typeRegistry` 
```ts
const todosResponse = await api.todos();
const rawTodos =  todosResponse.toJSON()
```
I get the same error and I have to add `typeRegistry` again. 

 ```ts
const todosResponse = await api.todos();
const rawTodos =  todosResponse.toJSON({
      typeRegistry: {
        findMessage(search: string) {
          if (search === "crypto.ed25519.PubKey") return PubKey;
        },
      },
   });
```

Is it possible to resolve `PubKey` every time when `crypto.ed25519.PubKey` is matched, but configure it only once? 
I can make changes only on client side, to server-side I have no access

**Comment by smaye81** [comment]
The `typeRegistry` can be defined anywhere and then just imported where needed:

```ts
// type-registry.ts
export const myTypeRegistry: IMessageTypeRegistry = {
  findMessage(search: string) {
    if (search === "crypto.ed25519.PubKey") return PubKey;
    return undefined;
  },
};
```

```ts
// different-file.ts
import { myTypeRegistry } from "./type-registry.js";

const todosResponse = await api.todos();
const rawTodos =  todosResponse.toJSON({
     typeRegistry: myTypeRegistry,
});
```

**Comment by RuslanGlaznyov** [comment]
Thanks for the fast response! I thought about it but I decided maybe a better solution exists

**Comment by timostamm** [comment]
There is another convenient alternative with `createRegistry()`:

```ts
import { TodosResponse, PubKey } from './proto-gen/.....'
import { createRegistry } from "@bufbuild/protobuf";

const todosResponse = await api.todos();
const rawTodos =  todosResponse.toJSON({
     typeRegistry: createRegistry(PubKey),
});
```

Of course it might still be useful to create the registry once and re-use the variable.

**Comment by smaye81** [comment]
@RuslanGlaznyov going to close this issue in light of the above examples. We've also updated our docs to provide an example using `createRegistry` (#597). If you get stuck on anything, though, feel free to reach out.
