### ISSUE TITLE
`findCustomScalarOption` but for repeated options?

### ISSUE THREAD

**Issue by Jayatubi** [bufbuild/protobuf-es#607]
It is valid to define a repeated options for a message such as:
```protobuf
extend google.protobuf.MessageOptions {
    repeated string bar = 10001;
}

message FooMessage {
   option(bar) = "hello";
   option(bar) = "world;
   ...
}
```

However, the function `findCustomScalarOption` could be used only to retrieve the first option since it was implemented as:
```javascript
function createBinaryReader(desc, extensionNumber) {
    const opt = desc.proto.options;
    let reader = undefined;
    if (opt !== undefined) {
        const unknownFields = protobuf_1.proto3.bin.listUnknownFields(opt);
        /* 
           This `unknownFields` contains all the repeated options attached to a message, with a same number.
           But only the first matched one will be returned
        */
        const field = unknownFields.find((f) => f.no === extensionNumber);
        if (field) {
            reader = new protobuf_1.BinaryReader(field.data);
        }
    }
    return reader;
}
```

How about to provide a new function, maybe named `findCustomRepeatedOptions`, to retrieve all the matched options?

For example:
```javascript
function createRepeatedBinaryReaders(desc, extensionNumber) {
  const opt = desc.proto.options;
  let readers = undefined;
  if (opt !== undefined) {
    const unknownFields = protobuf_1.proto3.bin.listUnknownFields(opt);
    readers = unknownFields
      .filter((f) => f.no === extensionNumber)
      .map(f => new protobuf_1.BinaryReader(field.data))
  }
  return readers;
}
```

**Comment by smaye81** [comment]
Hi @Jayatubi. You can retrieve repeated options using a message wrapper and the `findCustomMessageOption` function. For example:

```proto
// custom_options.proto
extend google.protobuf.MethodOptions {
  optional FooOptions foo_method_option = 50007;
}

message FooOptions {
  repeated string many = 1;
}

// foo_service.proto
import "custom_options.proto";

service FooService {
  rpc Get(GetRequest) returns (GetResponse) {
    option (foo_method_option) = { 
        many: ["a", "b", "c"],
    };
  }
}
```

You can retrieve the options using a generated type by first generating the file which defines the custom option type. Then, import and pass this type to the `findCustomMessageOption` function.

```ts
import { FooOptions } from "./gen/proto/custom_options_pb.js";

const option = findCustomMessageOption(method, 50007, FooOptions)

console.log(option);
/*
 * {
 *     many: ["a", "b", "c"],
 * }
 */
```

For more info, check out our plugin [docs](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md#message-options)

**Comment by Jayatubi** [comment]
> Hi @Jayatubi. You can retrieve repeated options using a message wrapper and the `findCustomMessageOption` function. For example:
> 
> ```proto
> // custom_options.proto
> extend google.protobuf.MethodOptions {
>   optional FooOptions foo_method_option = 50007;
> }
> 
> message FooOptions {
>   repeated string many = 1;
> }
> 
> // foo_service.proto
> import "custom_options.proto";
> 
> service FooService {
>   rpc Get(GetRequest) returns (GetResponse) {
>     option (foo_method_option) = { 
>         many: ["a", "b", "c"],
>     };
>   }
> }
> ```
> 
> You can retrieve the options using a generated type by first generating the file which defines the custom option type. Then, import and pass this type to the `findCustomMessageOption` function.
> 
> ```ts
> import { FooOptions } from "./gen/proto/custom_options_pb.js";
> 
> const option = findCustomMessageOption(method, 50007, FooOptions)
> 
> console.log(option);
> /*
>  * {
>  *     many: ["a", "b", "c"],
>  * }
>  */
> ```
> 
> For more info, check out our plugin [docs](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md#message-options)

The wrapper message option looks like but I think a plain repeated options should also be useful.

No need to change any of current interfaces. Just add a new one would be better.

**Comment by smaye81** [comment]
Yeah, understood. We actually explicitly opted against this for now to keep the API simpler and feel that the message wrapper is a viable alternative. Going to close this for now, since I don't see us implementing this anytime soon, but we will definitely reopen if we decide to revisit.

**Comment by timostamm** [comment]
@Jayatubi, the next release will support extensions. They can be used to retrieve repeated custom options as well. See https://github.com/bufbuild/protobuf-es/pull/666 and https://github.com/bufbuild/protobuf-es/pull/669.
