### ISSUE TITLE
Bug: Leading slash for type urls

### ISSUE THREAD

**Issue by grod220** [bufbuild/protobuf-es#617]
I have a grpc query [that returns a field](https://buf.build/cosmos/ibc/docs/main:ibc.core.client.v1#ibc.core.client.v1.IdentifiedClientState) with a `google.protobuf.Any`. At runtime it has the type url of: `/ibc.lightclients.tendermint.v1.ClientState`

The [corresponding message](https://buf.build/cosmos/ibc/docs/main:ibc.lightclients.tendermint.v1#ibc.lightclients.tendermint.v1.ClientState) it represents has the type url of: `type.googleapis.com/ibc.lightclients.tendermint.v1.ClientState`.

The discrepancy of type urls makes our registry not able to match these during the `Any` unpacking. Here is the logic that converts type urls to type names: https://github.com/bufbuild/protobuf-es/blob/f7375ad8b7e53efd3e3aafd39a17029487d812d1/packages/protobuf-test/src/gen/js/google/protobuf/any_pb.js#L211

This logic gives us:

```
Url: /ibc.lightclients.tendermint.v1.ClientState
Name: /ibc.lightclients.tendermint.v1.ClientState

Url: type.googleapis.com/ibc.lightclients.tendermint.v1.ClientState
Name: ibc.lightclients.tendermint.v1.ClientState

No match ❌
```

Can `Any.prototype.typeUrlToName` be expanded to handle leading slashes?

**Comment by timostamm** [comment]
The implementation assumes that type_url is a valid URL (optionally omitting the scheme) based on the [documentation](https://github.com/protocolbuffers/protobuf/blob/1a5cdb937826dbabc2c05872c5d7f1d918dea861/src/google/protobuf/any.proto#L128).

But it doesn't hurt to relax this a bit and accept just a leading slash. I just checked the Go implementation, and it also accepts this form.

**Comment by grod220** [comment]
Opened a PR, thanks for the review 🙏
