### ISSUE TITLE
Option for generate only types without static methods

### ISSUE THREAD

**Issue by Satont** [bufbuild/protobuf-es#662]
Might be useful for frontend declarations usage.

Current behavior with `target=dts` generates with static methods which is unnecessary.

**Comment by timostamm** [comment]
@Satont, the static methods are necessary to parse and serialize messages. A frontend would typically use them to issue a HTTP request and process a response. The methods are available in the generated JavaScript code, so it makes sense to include them in the typings as well. 

For frontend declaration usage, you can use `import type`, tree-shaking and code-splitting.

Closing, but please feel free to comment in case I misunderstood.
