### ISSUE TITLE
[feat] Option to generate enum with full prefix

### ISSUE THREAD

**Issue by vctqs1** [bufbuild/protobuf-es#673]
For example, the code below is generated from `buf`:

```
/**
 * @generated from enum usermgmt.common.ImportUserEventStatus
 */
export enum ImportUserEventStatus {
  /**
   * @generated from enum value: IMPORT_USER_EVENT_STATUS_WAITING = 0;
   */
  WAITING = 0,

  /**
   * @generated from enum value: IMPORT_USER_EVENT_STATUS_FINISHED = 1;
   */
  FINISHED = 1,

  /**
   * @generated from enum value: IMPORT_USER_EVENT_STATUS_FAILED = 2;
   */
  FAILED = 2,
}
```

However, in the backend (BE) code, the definition is as follows:

```
enum ImportUserEventStatus{
  IMPORT_USER_EVENT_STATUS_WAITING = 0;
  IMPORT_USER_EVENT_STATUS_FINISHED = 1;
  IMPORT_USER_EVENT_STATUS_FAILED = 2;
}
```
The question arises: Instead of generating and stripping out the`prefix`, should we consider adding opts to generate with the full key, such as`IMPORT_USER_EVENT_STATUS_FAILED` instead of just`FAILED`? 

This consideration is important because when storing data in the database, it uses the full name (`IMPORT_USER_EVENT_STATUS_FAILED`) instead of the stripped-out version. 

Using the full key `ImportUserEventStatus[key]` in the code makes it easier for mapping between the number and key instead of using longer methods like `proto3.getEnumType(ImportUserEventStatus).findName(<value>)`.

I also post my question in Slack before https://bufbuild.slack.com/archives/CRZ680FUH/p1699259433760749

**Comment by vctqs1** [comment]
I'm willing to make a change for this.

But it's preferable to align with the owner's perspective to ensure a change without any breaking in any section of the entire code generation process

**Comment by vctqs1** [comment]
Already did an PR for this proposal feature https://github.com/bufbuild/protobuf-es/pull/675

**Comment by vctqs1** [comment]
@timostamm ti
hi, sorry for bothering you, but could you help a look at this issue. Thank you

**Comment by timostamm** [comment]
Thanks for taking the initiative, @vctqs1! Please be aware that we are _very_ hesitant to add plugin option for the [reasons outlined in the FAQ](https://github.com/bufbuild/protobuf-es/blob/main/docs/faq.md#what-is-your-stance-on-adding-options-to-the-plugin). There needs to be a significant advantage to justify an option. 

How do strings for enum values end up in the database? Perhaps enumeration values are simply converted to strings, but this really depends on the language it's implemented in. For example, this will not work with the C# implementation (see the documentation [here](https://protobuf.dev/reference/csharp/csharp-generated/#enum)). It happens the protobuf-es takes a similar approach as the C# implementation, and generates short enum value names as well. 

In my experience, it can happen quite easily to accidentally lock yourself into a specific Protobuf implementation with custom mappings like that. You only notice once you start consuming with another implementation. If your backing writing to the database had been implemented in C#, you wouldn't have run into this specific issue, but it's possible that there will be other similar cases for other field values, not just enums. On the upside, Protobuf has the schema, reflection, and even code generation to solve issues like this. 

For your specific case, why don't you write a small function to parse the string values using reflection? Here is an example:

```ts
import { proto3 } from "@bufbuild/protobuf";

interface EnumObject {
  [key: number]: string;
  [k: string]: number | string;
}

export function parseEnumValueFromString<T extends EnumObject>(e: T, value: string): T[keyof T] | undefined {
  const enumValueInfo = proto3.getEnumType(e).findName(value);
  if (!enumValueInfo) {
    return undefined;
  }
  return enumValueInfo.no as T[keyof T];
}
```

**Comment by vctqs1** [comment]
@timostamm thank you, but do we have any changes to create in `protobuf-es` a function that convert sort enum strings to `long` version? 
for EX. when mapping enum value instead send to graphql's filter status = `SORT_NAME` it should filter status = `LONG_NAME`

**Comment by chrispine** [comment]
Thank you for your feedback, @vctqs1! I'm going to close this issue for now, but don't hesitate to reach out if you have any further questions/comments 😄

**Comment by geiseri** [comment]
We develop with python and C++ also so this add cognitive overhead for "The API is as follows, except for the case when it doesn't" when it comes to values.  I would encourage this to be reconsidered since its inconsistent with other generated code.

**Comment by geiseri** [comment]
I would also note that the prefix is kept in the cases where the enum would just be a number, further adding to the list of exceptions.

**Comment by jcready** [comment]
> its inconsistent with other generated code

You should take this issue up with the maintainers of protobuf as they already have this same inconsistency:
* [C#](https://protobuf.dev/reference/csharp/csharp-generated/#enum)
* [Objective-C](https://protobuf.dev/reference/objective-c/objective-c-generated/#enum)
* [Rust](https://github.com/protocolbuffers/protobuf/blob/73d96dba5478dc5b23b479c610bb1c675fed1144/src/google/protobuf/compiler/rust/naming.cc#L297-L313)


Their logic seems to be: the generated code should be idiomatic to the language and not necessarily to protobuf or any other generated code for other languages.

**Comment by geiseri** [comment]
All the languages we use (Go,Python,C++, and Dart ) just change case to match their own style. We don't use C# so I never noticed they kinda go their own way.    I guess they would also need to have special cases to deal with fields that would begin with a number if you remove the prefix.  Rust looks like they defer to what protoc has for options.   Really it was the inconsistent behavior in the ES bindings that was surprising that was all.
