### ISSUE TITLE
Comparing messages (Diff)

### ISSUE THREAD

**Issue by Nova38** [bufbuild/protobuf-es#726]
Currently the docs say that there is a function to compare to see if two messages are equal and it returns a Boolean value. Would it be possible to implement a similar function that returns the fields that are different and wether they have been removed, updated, or added (similar to https://github.com/unjs/ohash?tab=readme-ov-file#diffobj1-obj2-options)?

https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#comparing-messages

**Comment by timostamm** [comment]
Hey Thomas, it is definitely possible to implement such a function. 

Generated code includes information about every field of a message. Serialization and most other features of Protobuf-ES are implemented using this field information. It is (very lightly) documented [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#reflection-at-runtime). A diff function can take the same approach. 

We cannot focus on this feature right now, but you can easily write such a function for your own purposes, and are more than welcome to share it here in the form a gist or similar if you want to.
We are currently working on some updates that will

**Comment by chrispine** [comment]
I'm going to go ahead and close this issue, but feel free to re-open if needed. Thanks!
