### ISSUE TITLE
Using message as a value in Map seems to break deserialisation

### ISSUE THREAD

**Issue by Arttii** [bufbuild/protobuf-es#757]
Hi,

I am not sure if this is a misunderstanding on my part of some bug, but when using the following message definition:
```protobuf
message Stuff {
  map<string, data.structs.v1.Team> teams = 1;
  
}
```
nested in another message, leads to errors when decoding, I am getting the following error:
```
cannot decode map value for field package.structs.v1.Stuff.teams from JSON: object
```

The Team message itself has another map inside it, maybe that is somehow the culprit? The generation itself works fine.

Is this expected behaviour? Am I doing something wrong?

**Comment by timostamm** [comment]
Hey @Arttii, we have tests for map fields with messages (see [here](https://github.com/bufbuild/protobuf-es/blob/503e2f75087c047c1b7b9394206a19257cc6a082/packages/protobuf-test/extra/msg-maps.proto)) and are not aware of any issues with them.

Can you provide a reproducible example?

**Comment by Arttii** [comment]
So this wont have a problem even if the message has another map in it right? In that case, maybe its something on my side. Thanks for the support.
