### ISSUE TITLE
v2 Access

### ISSUE THREAD

**Issue by Travis-Spidertracks** [bufbuild/protobuf-es#780]
I see support for default fields in proto2 was added then reverted - I'm really interested in this feautre which i see is now on your v2 branch, is there any way to access this or a timeline for when an official release might be available?

Cheers!

**Comment by timostamm** [comment]
The feature for proto2 default values was moved into the v2 branch, which also supports editions, and access to options at runtime. 

We will publish it as a pre-release version in the next couple of days.

**Comment by timostamm** [comment]
Travis, a pre-release is now available with [v2.0.0-alpha.1](https://github.com/bufbuild/protobuf-es/releases/tag/v2.0.0-alpha.1)

Please feel free to open an issue for feedback, or reach out via [Slack](https://buf.build/links/slack).
