### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by bufdev** [bufbuild/protobuf-es#86]
The docs say:

> We implement all proto2 features, except for extensions and the text format.

I don't think we can ignore extensions - what does the core js do?

**Comment by SyrieBianco** [comment]
Replaced by TCN-61

**Comment by fubhy** [comment]
Any news on this? This is currently my main blocker for implementing message validation (using https://github.com/bufbuild/protoc-gen-validate)

https://github.com/bufbuild/connect-web/issues/270

Is this being worked on or can I lend a hand here? If so, I'd love some pointers (tried to read through the code generator request => descriptor set creation code but am a bit lost to be honest :-)

**Comment by timostamm** [comment]
Hey Sebastian, `findCustomMessageOption()` is indeed the way to go for now!

**Comment by fubhy** [comment]
Yeah, I built my own version of that before I found that in your code :-D. Sorry for the noise.

**Comment by zfedoran** [comment]
@fubhy are you able to share what you've done to get message validation running using `findCustomMessageOption()`?

**Comment by rofrankel** [comment]
Just commenting to +1 the issue - I'd benefit from extension support (specifically, message and field options).

**Comment by timostamm** [comment]
Support for extensions was just released in [v1.7.0](https://github.com/bufbuild/protobuf-es/releases/tag/v1.7.0).

Extensions can be used to retrieve custom Protobuf options from descriptors, [for example in a plugin](https://github.com/bufbuild/protobuf-es/blob/main/docs/writing_plugins.md#using-custom-protobuf-options). But it's not possible yet to retrieve options at runtime from generated code. We do have concrete plans for this feature though, and we'll keep the issue https://github.com/bufbuild/protobuf-es/issues/397 updated.
