### ISSUE TITLE
@bufbuild/protobuf proto3 serialization regression: throw error when serializing oneof property with `undefined` value

### ISSUE THREAD

**Issue by nicoraynaud** [bufbuild/protobuf-es#864]
Hi all !

We are facing an issue with a `oneof` message property having a string value being set to `undefined` is triggering an error since version `v1.8.0`.

As an example, here is a proto3 message for reproducing the error.
```
syntax = "proto3";

message MyMessageWithOneOf {
  oneof token {
    string first_token = 1;
    string second_token = 2;
  }
}
```

And here is the code setting an undefined value (in TS, after generating the proto objects):
```
const message = { value: undefined, case: 'firstToken' }
```

1. Before version 1.8.0 this would successfully be serialized in the request, as we can see in [binary-format-proto3.ts](https://github.com/bufbuild/protobuf-es/blob/31daf8c6778e165e55bec03c48bce95fe801adc9/packages/protobuf/src/private/binary-format-proto3.ts#L48), where there is no validation on the field value and it essentially gets set to `undefined`.
2. Since version 1.8.0, after [a commit aiming at merging proto2 and proto3](https://github.com/bufbuild/protobuf-es/commit/ca332ba77fe41257f56445ff5c818e569df4cc84) serializers, this [code in binary-format.ts](https://github.com/bufbuild/protobuf-es/blob/v1.8.0/packages/protobuf/src/private/binary-format.ts#L363) is now called and we can see that this triggers an assertion error since it does not accept undefined values.

This, to me, seems like a breaking change that could require the change to a major version.

Is there a way we could fix this behaviour to be backward compatible (a patch maybe) ? If not, we should at least update the documentation or the changelog to reflect how this change could break for existing code ?

**Comment by timostamm** [comment]
Hey Nicolas, it looks like this is a misunderstanding regarding how the oneof representation works.

The property `case` is the discriminator for the union. If it's `undefined`, this means that no field of the oneof group is selected, and that there is no value. Conversely, if `case` is specified, the field with this name is selected and has the specified `value`, meaning that `value` cannot be undefined.

With your example, this means that all of the the following assignments are valid:

```ts
import { MyMessageWithOneOf } from "./gen/...";

const msg = new MyMessageWithOneOf();
msg.token = { case: 'firstToken', value: "abc" };
msg.token = { case: 'secondToken', value: "def" };
msg.token = { case: undefined }; // `value: undefined` can be omitted here
```

But `{value: undefined, case: 'firstToken'}` is not valid, and will raise a compile time error with TypeScript.

I am sorry this was not obvious to you. Let me know if we can clarify this in our [documentation](https://github.com/bufbuild/protobuf-es/blob/ff7eaa6fa3ff8ea3d8bd63c2ec09220562c6b0fd/docs/runtime_api.md#accessing-oneof-groups).

**Comment by nicoraynaud** [comment]
Hiu @timostamm !

Thank you for taking the time to review this.

I kind of agree that we should not be sending `undefined` but the code I shared above worked with versions prior to `v1.8.0`. We discovered it when we upgraded to the latest version and the code was now throwing an `assert` error upon serialization. We were setting the case properly and an `undefined` value without knowing, and this was serialized as an empty value.

To follow up with your example above, up until the change, we could do this successfully:
```
const myValue: string | undefined = undefined;
msg.token = { case: 'secondToken', value: myValue };
```

This is why I felt like this is more of a breaking change 🤔

**Comment by timostamm** [comment]
Sometimes a bug is widely depended on, and fixing it in a patch or minor release would be inadequate. 
Clearly you're affected by the change, but I do not get the impression that the previous behavior was _widely_ depended on. Apologies for the inconvenience.
