### ISSUE TITLE
Tree-shakeable enums

### ISSUE THREAD

**Issue by bhollis** [bufbuild/protobuf-es#891]
**Is your feature request related to a problem? Please describe.**

"Tree-shaking", or more simply dead-code elimination, is a mechanism implemented by various JS bundlers or minifiers to make the resulting code bundle as small as possible. The goal is that any code that is not used in the consuming app should not appear in the bundle - for example, if an app depends on a large service client library, but only uses a few methods of that library, the code for the types and methods that aren't used should not appear in the final bundle, because they add to download weight but provide no benefit to the app.

Here's an example from protobuf-es. Given a proto enum:

```proto
enum KnownRegex {
  KNOWN_REGEX_UNSPECIFIED = 0;
  KNOWN_REGEX_HTTP_HEADER_NAME = 1;
  KNOWN_REGEX_HTTP_HEADER_VALUE = 2;
}
```

protoc-gen-connect-es generates TS code:

```ts
export enum KnownRegex {
  UNSPECIFIED = 0,
  HTTP_HEADER_NAME = 1,
  HTTP_HEADER_VALUE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(KnownRegex)
proto3.util.setEnumType(KnownRegex, "buf.validate.KnownRegex", [
  { no: 0, name: "KNOWN_REGEX_UNSPECIFIED" },
  { no: 1, name: "KNOWN_REGEX_HTTP_HEADER_NAME" },
  { no: 2, name: "KNOWN_REGEX_HTTP_HEADER_VALUE" },
]);
```

which in turn generates this JS code:

```js
export var KnownRegex;
(function (KnownRegex) {
    KnownRegex[KnownRegex["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    KnownRegex[KnownRegex["HTTP_HEADER_NAME"] = 1] = "HTTP_HEADER_NAME";
    KnownRegex[KnownRegex["HTTP_HEADER_VALUE"] = 2] = "HTTP_HEADER_VALUE";
})(KnownRegex || (KnownRegex = {}));
// Retrieve enum metadata with: proto3.getEnumType(KnownRegex)
proto3.util.setEnumType(KnownRegex, "buf.validate.KnownRegex", [
    { no: 0, name: "KNOWN_REGEX_UNSPECIFIED" },
    { no: 1, name: "KNOWN_REGEX_HTTP_HEADER_NAME" },
    { no: 2, name: "KNOWN_REGEX_HTTP_HEADER_VALUE" },
]);
```

There are a few problems here:

1. TypeScript Enums are already [difficult to eliminate when unused](https://www.github.com/microsoft/TypeScript/issues/27604) because they're constructed via an IIFE. 
1. Since `proto3.util.setEnumType` could have global side effects, it cannot be eliminated even if `KnownRegex` is not used anywhere, which means `KnownRegex` cannot be eliminated. 

**Describe the solution you'd like**
I'd like the generated code to be changed in such a way that it can be eliminated when not referenced. One possibility:

```ts
export const KnownRegex = {
  UNSPECIFIED: 0,
  HTTP_HEADER_NAME: 1,
  HTTP_HEADER_VALUE: 2,
} as const;

export const KnownRegex_Info: [typeName: string, values: Omit<EnumValueInfo, "localName">[]] = ["buf.validate.KnownRegex", [
  { no: 0, name: "KNOWN_REGEX_UNSPECIFIED" },
  { no: 1, name: "KNOWN_REGEX_HTTP_HEADER_NAME" },
  { no: 2, name: "KNOWN_REGEX_HTTP_HEADER_VALUE" },
]];
```

Assuming the generated code used `KnownRegex_Info` wherever it's needed, this code is tree-shakeable, with the bonus that enum values can often be inlined entirely, and the extra info used by protobuf-es is only present in the bundle wherever those features are used.

**Describe alternatives you've considered**

There are a bunch of different options around what code could be generated, with different tradeoffs. Mostly it's useful to try them out in the [Terser REPL](https://try.terser.org) to see how they fare.

**Additional context**

If this is interesting, I'd be happy to file some other issues around generated code size and tree-shaking.

**Comment by bhollis** [comment]
Never mind - I just discovered the `target=js+dts` option which is exactly what I need.

**Comment by timostamm** [comment]
Thanks for the great issue description, Ben.

Unfortunately, we cannot annotate the call to `setEnumType` as pure, as it is a side effect. Glad you found `target=js+dts`!
