### ISSUE TITLE
`PlainMessage<Empty>` is `{}`, meaning any non-nullish value

### ISSUE THREAD

**Issue by haines** [bufbuild/protobuf-es#892]
I think it's a little bit unfortunate that `PlainMessage<Empty>` (or `PlainMessage` of any user-defined empty message) reduces to `{}`, because to quote typescript-eslint

>Don't use `{}` as a type. `{}` actually means "any non-nullish value".
>- If you want a type meaning "any object", you probably want `object` instead.
>- If you want a type meaning "any value", you probably want `unknown` instead.
>- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
>- If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead.

The problem is that TypeScript won't prevent you from doing nonsensical things like

```typescript
const empty: PlainMessage<Empty> = 42;
```

I don't think it's really a bug, given that you can also do stuff like `new Empty(42)` without a runtime error, but it might be nicer if `PlainMessage<Empty>` produced `Record<string, never>` instead?

**Comment by timostamm** [comment]
This is fixed with [version 2](https://github.com/bufbuild/protobuf-es/releases/tag/v2.0.0):

```ts
import type { Empty } from "./gen/example_pb";

const empty: Empty = 42; // TS2322: Type number is not assignable to type Message<"Empty">
```

**Comment by haines** [comment]
Awesome, thanks @timostamm!
