### ISSUE TITLE
Missing `Timestamp` typing for TS

### ISSUE THREAD

**Issue by futurethang** [bufbuild/protobuf-es#951]
After updating my dependency to v2.0 in a React project, I have lost the capability of importing a `Timestamp` type. 

Formerly I could use:
```typescript
import { Timestamp } from '@bufbuild/protobuf';

interface IGroupRoleMapping {
  id: string;
  group: string;
  roleIds: string[];
  createdAt?: string;
  updatedAt?: Timestamp;
}
export default IGroupRoleMapping;
```

but it is no longer an exported memeber:
`Module '"@bufbuild/protobuf"' has no exported member 'Timestamp'.ts(2305)`

Any guidance is appreciated!

**Comment by smaye81** [comment]
Hi @futurethang. The import path actually changed a bit with v2. It should be `@bufbuild/protobuf/wkt`. See docs [here](https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#well-known-types).

**Comment by futurethang** [comment]
Followup on this, another missing type is `PartialMessage`. This is not listed with well known types, but is prevalent in previous protos
