### ISSUE TITLE
ServiceType in  "@bufbuild/protobuf": "^2.0.0", Conflict Error

### ISSUE THREAD

**Issue by junmingchen123** [bufbuild/protobuf-es#959]
`// use-client.ts
import { useMemo } from "react";
import { ServiceType } from "@bufbuild/protobuf";
import { createConnectTransport } from "@connectrpc/connect-web";
import { createPromiseClient, PromiseClient } from "@connectrpc/connect";

// This transport is going to be used throughout the app
const transport = createConnectTransport({
  baseUrl: "https://demo.connectrpc.com",
});

/**
* Get a promise client for the given service.
*/
export function useClient<T extends ServiceType>(service: T): PromiseClient<T> {
  // We memoize the client, so that we only create one instance per service.
  return useMemo(() => createPromiseClient(service, transport), [service]);
}`
Dear author, I hope you can tell me what to do. Now there is a conflict. Sorry to bother you. The above is the ServiceType used in the official sample code, but when I use version 2.0.0, there is no ServiceType. However, even if I want to lower the version, in the generated api code, there is @bufbuild/protobuf/codegenv1 in the import. If you do not use version 2.0.0 or above, codegenv1 will not have this, and this will report an error. Now, when I use 2.0.0, there is no error. When I try to use the interface, an error is reported again.
This is Error

`✘ [ERROR] No matching export in "node_modules/@bufbuild/protobuf/dist/esm/index.js" for import "protoBase64"

    node_modules/@connectrpc/connect/dist/esm/protocol-connect/error-json.js:25:9:
      25 │ import { protoBase64 } from "@bufbuild/protobuf";
         ╵          ~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@bufbuild/protobuf/dist/esm/index.js" for import "Message"

    node_modules/@connectrpc/connect/dist/esm/protocol-connect/handler-factory.js:14:9:
      14 │ import { Message, MethodIdempotency, MethodKind, protoBase64, } from "@bufbuild/protobuf";
         ╵          ~~~~~~~

✘ [ERROR] No matching export in "node_modules/@bufbuild/protobuf/dist/esm/index.js" for import "MethodIdempotency"

    node_modules/@connectrpc/connect/dist/esm/protocol-connect/handler-factory.js:14:18:
      14 │ import { Message, MethodIdempotency, MethodKind, protoBase64, } from "@bufbuild/protobuf";
         ╵                   ~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@bufbuild/protobuf/dist/esm/index.js" for import "MethodKind"

    node_modules/@connectrpc/connect/dist/esm/protocol-connect/handler-factory.js:14:37:
      14 │ import { Message, MethodIdempotency, MethodKind, protoBase64, } from "@bufbuild/protobuf";
         ╵                                      ~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@bufbuild/protobuf/dist/esm/index.js" for import "protoBase64"

    node_modules/@connectrpc/connect/dist/esm/protocol-connect/handler-factory.js:14:49:
      14 │ import { Message, MethodIdempotency, MethodKind, protoBase64, } from "@bufbuild/protobuf";`

This is pachakge.json

`"@bufbuild/connect": "^0.13.0",
    "@bufbuild/protobuf": "^2.0.0",
    "@connectrpc/connect": "^1.4.0",
    "@connectrpc/connect-web": "^1.4.0",`

**Comment by timostamm** [comment]
Hey @junmingchen123, Connect-ES does not support Protobuf-ES version 2 yet. We will update it shortly.

If you want to give it a try before we cut a stable release, you can use the [alpha version](https://github.com/connectrpc/connect-es/releases/tag/v2.0.0-alpha.1):

```
npm install @connectrpc/connect@alpha @connectrpc/connect-web@alpha @bufbuild/protobuf@latest @bufbuild/protoc-gen-es@latest
```

**Comment by junmingchen123** [comment]
Thanks for your reply, but ServiceType is still not available in @bufbuild/protobuf@latest, which is now 2.0.0, and I will replace
` 
import { createPromiseClient, PromiseClient } from "@bufbuild/connect";
`
 with
`
 import { createPromiseClient, PromiseClient } from "@connectrpc/connect"; 
`
because there is no ServiceType, so 
`
export function useClient<T extends ServiceType>(service: T): PromiseClient<T> {
return useMemo(() => createPromiseClient(service, transport), [service]);
}
 `
The T type here reports an error, I tried to use type ServiceType = any; No, I don't know what I should do，The current package.json is：
` 
"@bufbuild/protobuf": "^2.0.0",
    "@bufbuild/protoc-gen-es": "^2.0.0",
    "@connectrpc/connect": "^2.0.0-alpha.1",
    "@connectrpc/connect-web": "^2.0.0-alpha.1",
`
Can you give me some advice, I really need information

**Comment by kakuiho** [comment]
confirm it on 
```
    "@bufbuild/protobuf": "^2.2.2",
    "@connectrpc/connect": "^2.0.0",
    "@connectrpc/connect-web": "^2.0.0",
```


replace `import { ServiceType } from "@bufbuild/protobuf";`
with  `import { DescService } from "@bufbuild/protobuf";`
walk around this issue and it works, thanks @junmingchen123

**Comment by timostamm** [comment]
Ah, we missed to update this example, thanks for the shout.

Updating the docs here: https://github.com/connectrpc/connectrpc.com/pull/227

Related update to MIGRATING.md: https://github.com/connectrpc/connect-es/pull/1343
