### ISSUE TITLE
question: how can I migrate from `PlainMessage` and `toPlainMessage` to the v2's equivalent?

### ISSUE THREAD

**Issue by alissa-tung** [bufbuild/protobuf-es#960]

**Comment by timostamm** [comment]
Hey Alissa, the types generated by v2 are equivalent to plain messages in v1.

For example, with this Protobuf file:

```protobuf
syntax = "proto3";
message User {
  string first_name = 1;
}
```

We'll generate:

```typescript
/**
 * @generated from message example.User
 */
export declare type User = Message<"example.User"> & {
  /**
   * @generated from field: string first_name = 1;
   */
  firstName: string;
};
```

You can basically replace `PlainMessage<User>` with `User`. If you create a proto3 message with `create(UserSchema)`, the returned object is already a plain object, and there is no need to use `toPlainMessage()` anymore. 

The only difference is that `User` has a property `$typeName`, which is a simple string with the full name of the message, for example `"example.User"`. This property makes sure you don't pass the wrong message to a function by accident.

**Comment by alissa-tung** [comment]
> Hey Alissa, the types generated by v2 are equivalent to plain messages in v1.
> 
> For example, with this Protobuf file:
> 
> ```proto
> syntax = "proto3";
> message User {
>   string first_name = 1;
> }
> ```
> 
> We'll generate:
> 
> ```ts
> /**
>  * @generated from message example.User
>  */
> export declare type User = Message<"example.User"> & {
>   /**
>    * @generated from field: string first_name = 1;
>    */
>   firstName: string;
> };
> ```
> 
> You can basically replace `PlainMessage<User>` with `User`. If you create a proto3 message with `create(UserSchema)`, the returned object is already a plain object, and there is no need to use `toPlainMessage()` anymore.
> 
> The only difference is that `User` has a property `$typeName`, which is a simple string with the full name of the message, for example `"example.User"`. This property makes sure you don't pass the wrong message to a function by accident.

Thank you!
