### ISSUE TITLE
Why doesn't JsonValue support bigint type?

### ISSUE THREAD

**Issue by aki-caffeine** [bufbuild/protobuf-es#968]
I am using bufbuild to transpile to Typescript.
The .proto file contains a field that uses the uint64 type, which is converted to the bigint type and output as a .tds file, as written [here](https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#why-use-bigint-to-represent-64-bit-integers).

However, I encountered a problem. The JsonValue type does not contain the bigint type, so the bigint type field obtained as a result of the API cannot be used as a Json-Request.

```
/**
 * Represents any possible JSON value:
 * - number
 * - string
 * - boolean
 * - null
 * - object (with any JSON value as property)
 * - array (with any JSON value as element)
 */
export type JsonValue = number | string | boolean | null | JsonObject | JsonValue[];
/**
 * Represents a JSON object.
 */
export type JsonObject = {
    [k: string]: JsonValue;
};

```

I think there are many cases where the result obtained from the API is stored in the Request, so do I need to convert bigint to string and make an API request?

**Comment by srikrsna-buf** [comment]
Hey! The results obtained from the API should be of the message type. To get the `JsonValue` type, you need to use the `toJson` function. It doesn't have `bigint` because `JSON.parse` and `JSON.stringify` do not support `bigint` types, which is typically where the json values are used.

Can you tell me a bit more about how you are trying to use the type?

**Comment by aki-caffeine** [comment]
Hi @srikrsna-buf  Thanks for your quick response.

I define an index signature in my code that has the same information as the API Request type output by bufBuild. For example, like this.

```
type requestType = {
        messageSeq: bigint;
        content: string | null;
    }

const requestJson: requestType = {
    messageSeq : 10000,
    content : 'Hello!'
}
```

And because message type has a convenient method `fromJson`, I tried to put the above typed variable directly into the `fromJson` argument. At this time, I found that `JsonValue` did not contain `bigint`.


However, your response gave me some interesting information.
> JSON.parse and JSON.stringify do not support bigint types

I'm embarrassed to say this, but I didn't know about the above specification until now. Thank you for letting me know.

For now, I've concluded that when using `fromJson`, you should not include huge numbers that cannot be handled by the `number` type. I'm thinking that if you think you might transpile the .proto file to typescript, it might be better to use `string` instead of `uint64`.

**Comment by srikrsna-buf** [comment]
No need to use `fromJson`, if the fields match, you can directly use `create` and pass the `requestType` to it. It will accept `bigint` and when you use `toJson` on the returned value it will handle `bigint`.

Closing the issue for now, feel free reach out again if you find any issue.
