### ISSUE TITLE
protobuf v2 Timestamp fails in combination with MSW and Vitest

### ISSUE THREAD

**Issue by hollanderbart** [bufbuild/protobuf-es#977]
When trying to upgrade to protobuf v2, we use mock functions to use in our test cases.

Previously we used `timestamp: Timestamp.fromDate(new Date())`

Now we use `timestamp: timestampFromDate(new Date())`. But this will create the following error in combination with MSW.

```
  http.post(createBackendUrl('GetDevice'), async () =>
    HttpResponse.json(generateDevice()),
  ),
```

Removing the timestamp will clear the error, so that would imply the error comes from the conversion of a Timestamp to a JSON value, that will be used by MSW.

```
Error handled by React Router default ErrorBoundary: ConnectError: [unknown] cannot decode message google.protobuf.Timestamp from JSON: message google.protobuf.Timestamp
{
  rawMessage: 'cannot decode message google.protobuf.Timestamp from JSON: message google.protobuf.Timestamp',
  code: 2,
  metadata: Headers {},
  details: [],
  cause: Error: cannot decode message google.protobuf.Timestamp from JSON: message google.protobuf.Timestamp
      at timestampFromJson 
}
```

If I see the snapshot differences, I notice that previously it would create a Date string, while now it's an object. 

<img width="355" alt="image" src="https://github.com/user-attachments/assets/36854e37-b938-4a7b-b72c-2742da1d445b">

What is the best approach to work with protobuf v2 and MSW?

**Comment by timostamm** [comment]
Hey Bart, you'll have to convert the message to a JSON object first:

```ts
const device = generateDevice();
const json = toJson(DeviceSchema, device);
return HttpResponse.json(json),
```

In v1, generated classes implement a `toJSON` method, which is automatically called by `JSON.stringify`. It's a bit of a double edged sword: It can be convenient, but it doesn't work with `google.protobuf.Any`, and the behavior can be surprising. So we're not too sad that messages in v2 no longer implement the method (since messages are no longer classes).

**Comment by hollanderbart** [comment]
Thanks, that works. I'm wondering if that I didn't follow the upgrade guide correctly, or that this is maybe missing.

**Comment by timostamm** [comment]
Yes, we should note this in the guide. 👍
