### ISSUE TITLE
I can use buf.build/bufbuild/es with axios instead of using connectpb

### ISSUE THREAD

**Issue by levinhne** [bufbuild/protobuf-es#981]
I can use buf.build/bufbuild/es with axios instead of using connectpb

Ex:
```typescript
import { CreateTodoRequest, CreateTodoResponse, Todo } from "@/client/types/proto/todo/v1/todo_pb";
import axios, { AxiosResponse } from "axios";

export const createTodo = async (data: Todo) => {
  const req : CreateTodoRequest = {
    $typeName: "todo.v1.CreateTodoRequest",
    todo: data,
  }
  const response = await axios.post<CreateTodoResponse, AxiosResponse<CreateTodoResponse>, CreateTodoRequest>(
    "http://localhost:8088/api/v1/todos",
    req,
  );
  return response.data;
}
```
Thanks!

**Comment by timostamm** [comment]
Yes, you can use the generated code in many ways. You could even [write your own plugin](https://github.com/bufbuild/protobuf-es/blob/v2.1.0/MANUAL.md#writing-plugins) to generate your example.

Please be aware that passing `CreateTodoRequest` to `axios.post` has limitations. This will serialize the message to JSON with `JSON.stringify`, which will not serialize fields with `bytes`, `double`, and 64-bit integers correctly. The JSON standard does not support BigInt, Uint8Array, and infinite numbers. To avoid this issue, use `toJson` for the request, and `fromJson` for the response.
